import { restbaseurl } from './constants';

export const resturls = {
  obtainFavIconAndTitle: 'auth_service/obtainFavIconAndTitle',
  obtainManualPublishDetails: 'corporateTrainingBatch/obtainManualPublishDetails',
  login: 'auth_service/login_user',
  getUserDetails: 'auth_service/get_all_users',
  getAllGroupDetails: '/auth_service/get_all_groups',
  getSingleUserDetails: 'auth_service/get_user',
  CreateNewGroup: '/auth_service/create_group',
  updateUser: '/auth_service/update_user',
  updateGroup: '/auth_service/update_group/',
  allGeneralRequests: '/request_service/all_general_requests',
  allGeneralRequestCount: '/request_service/all_general_request_count',
  allHardwareRequest: '/request_service/all_request',
  allHardwareRequestCount: '/request_service/all_request_count',
  getHardwareRequestById: 'request_service/get_hardware_request_by_id',
  allIncident: '/incident_service/all_incident',
  getOpenIncident: '/incident_service/get_open_incident',
  getIncidentByAssignedTo: '/incident_service/get_incident_by_assignedto/',
  getAllServers: 'cmdb_service/get_all_servers/',
  getAllItems: '/cmdb_service/get_all_items',
  postConfigurationItem: '/cmdb_service/post_configuration_item',
  postSoftwareConfigurationItem: '/cmdb_service/post_software_item',
  CreateClass: '/cmdb_service/create_class',
  obtainItemRequirementList: 'cmdb_service/fetch_class_names_and_ids_by_item_requirement',
  classCatecoryItems: '/cmdb_service/fetch_class_categories',
  obtainFormFieldData: '/cmdb_service/fetch_class_category_attributes',
  createNewIncident: '/incident_service/post_incident',
  updateIncident: '/incident_service/update-incident/',
  getIncidentById: '/incident_service/get_incident_by_id/',
  fetchUserIncident: '/incident_service/fetch_incident',
  CreateClassInstance: '/cmdb_service/create_class_instance',
  addUser: '/auth_service/add_user',
  obtainCategoryInstance: '/cmdb_service/fetch_class_items',
  obtainCategoryAttributes: '/cmdb_service/fetch_class_instance',
  updateClassInstance: '/cmdb_service/update_class_instance',
  allIncidentCount: '/incident_service/all_incident_count',
  deleteClassCategory: '/cmdb_service/delete_class_category',
  uploadUserExcel: '/auth_service/upload_user_excel',
  removeUser: '/auth_service/delete_user',
  azure_login: 'auth_service/azure_login',
  getAccessToken: 'auth_service/azure/get_access_token',
  FetchAllOrganizations: 'auth_service/fetch_all_organizations',
  FetchGroupDetails: 'auth_service/groups',
  AdLogin: '/auth_service/ldap_connection_test',
  getADUser: '/auth_service/login_AD_user',
  getAllADUsers: '/auth_service/get_all_AD_users',
  getCategory: '/incident_service/category',
  fetchGroups: '/auth_service/fetch_groups',
  fetchAdminGroup: '/auth_service/fetch_admin_group',
  obtainAssignGroups: '/auth_service/filtered_group_names',
  assignedIncidents: '/incident_service/assigned_incidents',
  openIncidents: '/incident_service/open_incidents',
  userFetchGroups: '/auth_service/fetch_groups',
  createCatalog: '/request_service/catalogues/create_catalog',
  catelogueAddCategory: '/request_service/catalogues/add_category',
  addSubCategory: '/request_service/catalogues/add_sub_category',
  fetchSubcategoryById: '/request_service/catalogues/fetch_subcategory_by_id',
  fetchCatalogueById: '/request_service/catalogues/fetch_catalogue_by_id',
  fetchCategoryById: '/request_service/catalogues/fetch_category_by_id',
  fetchAllCatalogues: '/request_service/catalogues/fetch_all_catalogues',
  fetchAllClassInstances: '/cmdb_service/fetch_all_class_instances',
  createCatalogItem: '/request_service/create_catalog_item',
  updateCatalogItems: '/request_service/update_catalog_item',
  fetchCatalogItem: '/request_service/fetch_catalog_item',
  fetchAllCatalogitems: '/request_service/fetch_all_catalog_items',
  getBySubCategory: '/request_service/getBySubCategory',
  getByCategory: '/request_service/getByCategory',
  createRequestInstance: '/request_service/create_request_instance',
  catalogReqItmCount: '/request_service/fetch_current_request_number',
  getRequestOpenedBy: '/request_service/get_request_opened_by',
  updateRequestInstance: '/request_service/update_request_instance',
  fetchRequestInstance: '/request_service/fetch_request_instance',
  deleteRequestInstance: '/request_service/delete_request_instance/',
  userDashboardService: '/dashboard_service/user_dashboard/user_incident_request_stats',
  adminDashboardService: '/dashboard_service/admin_dashboard/admin_incident_stats',
  fetchAllRequestInstance: '/request_service/fetch_all_requests_instances',
  addNotes: '/incident_service/notes/'
};

export const successurl = `${restbaseurl}student/success`;
export const failureurl = `${restbaseurl}student/failure`;

export const dummyurl = 'http://dummy.restapiexample.com/api/v1/employees';
